name: Migrate - Production
on:
  push:
    branches: [main]

jobs:
  deploy:
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'npm'
      - name: Apply all pending migrations to the database
        working-directory: ./apps/api
        run: npx prisma migrate deploy --schema=./prisma/schema.prisma
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
